export const endpoints = {
  authSignIn: '/api/auth/signin',
  authVerify: '/api/auth/verify',
  authGoogle: '/api/auth/google',
  authApple: '/api/auth/apple',
  authGoogleCode: '/api/auth/google/code',
  authRefresh: '/api/auth/refresh',
  authAccountDelete: '/api/auth/account',
  storesMe: '/api/stores/me',
  storesMine: '/api/stores/mine',
  storesStaff: '/api/stores/staff',
  stores: '/api/stores',
  inboxAiSettings: (storeId: number) => `/api/stores/${storeId}/inbox-ai/settings`,
  whatsappReplyMode: (conversationId: number, storeId: number) =>
    `/api/whatsapp/chats/${conversationId}/reply-mode?store_id=${storeId}`,
  instagramReplyMode: (conversationId: number, storeId: number) =>
    `/api/instagram/chats/${conversationId}/reply-mode?store_id=${storeId}`,
  paymentConfig: '/api/stores/me/payment-config',
  paymentConfigRazorpayTestCheckout: '/api/stores/me/payment-config/razorpay/test-checkout',
  paymentConfigRazorpayVerifyTest: '/api/stores/me/payment-config/razorpay/verify-test',
  notificationPreferences: '/api/stores/me/notification-preferences',
  pushToken: '/api/stores/me/push-token',
  products: '/api/products',
  categories: '/api/categories',
  industries: '/api/industries',
  orders: '/api/orders',
  customers: '/api/customers',
  uploadProductImages: '/api/uploads/product-images',
  whatsappChats: '/api/whatsapp/chats',
  whatsappSend: '/api/whatsapp/send',
  whatsappSendMedia: '/api/whatsapp/send-media',
  whatsappForward: '/api/whatsapp/forward',
  whatsappMediaUpload: '/api/whatsapp/media/upload',
  whatsappConnect: '/api/whatsapp/connect',
  whatsappCompleteOnboarding: '/api/whatsapp/complete-onboarding',
  whatsappConnectionStatus: '/api/whatsapp/connection-status',
  whatsappSync: '/api/whatsapp/sync',
  whatsappOffboard: '/api/whatsapp/offboard',
  whatsappClearChatHistory: '/api/whatsapp/clear-chat-history',
  instagramConnect: '/api/instagram/connect',
  instagramConnectionStatus: '/api/instagram/connection-status',
  instagramSubscribeWebhooks: '/api/instagram/subscribe-webhooks',
  instagramClearChatHistory: '/api/instagram/clear-chat-history',
  instagramChats: '/api/instagram/chats',
  instagramSend: '/api/instagram/send',
  instagramSendMedia: '/api/instagram/send-media',
  instagramMediaUpload: '/api/instagram/media/upload',
  instagramForward: '/api/instagram/forward',
  subscriptionsPricing: '/api/subscriptions/pricing',
  subscriptionsCheckout: '/api/subscriptions/checkout',
  subscriptionsVerify: '/api/subscriptions/verify',
  subscriptionsStatus: '/api/subscriptions/status',
  subscriptionsAppleSync: '/api/subscriptions/apple/sync',
  supportConversation: '/api/support/conversation',
  supportMessages: (conversationId: number) =>
    `/api/support/conversations/${conversationId}/messages`,
  supportEscalate: (conversationId: number) =>
    `/api/support/conversations/${conversationId}/escalate`,
  supportClose: (conversationId: number) =>
    `/api/support/conversations/${conversationId}/close`,
  supportAdminMe: '/api/support/admin/me',
  supportAdminConversations: '/api/support/admin/conversations',
  supportAdminMessages: (conversationId: number) =>
    `/api/support/admin/conversations/${conversationId}/messages`,
  supportAdminReplyMode: (conversationId: number) =>
    `/api/support/admin/conversations/${conversationId}/reply-mode`,
  supportAdminClose: (conversationId: number) =>
    `/api/support/admin/conversations/${conversationId}/close`,
  supportUnread: '/api/support/unread',
  supportMarkRead: (conversationId: number) =>
    `/api/support/conversations/${conversationId}/read`,
  supportAdminSummary: '/api/support/admin/summary',
  supportAdminMarkRead: (conversationId: number) =>
    `/api/support/admin/conversations/${conversationId}/read`,
} as const
